<div>
	<h3>邮件统计信息</h3>
	<p>
		<table border="1" cellspacing="0" >
			<thead>
				<th>用户注册数</th>
				<th>订单总数</th>
				<th>商品总数</th>
			</thead>
			<tbody>
				<tr>
					<td>{{$m_nums}}</td>
					<td>{{$order_nums}}</td>
					<td>{{$goods_nums}}</td>
				</tr>
			</tbody>
		</table>
	</p>
</div>
